title: "Buttons"
description: |
  Buttons should be used in situations where a call to action is required. Only use buttons when necessary as it shouldn't take attention away from more important content.

patterns:
  basic:
    title: "Basic"
    description: |
      Default button to be used for all ganeral uses. From banner call to actions, to generic confirmations. This is the all purpose button.
    background: "--color-primary-medium"
    fields:
      - name: text
        type: string
        example: "Try Now"
      - name: url
        type: url
        example: "/account/"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically used for the search button.
    background: "--color-primary-medium"

  btn-light:
    title: "Light"
    description: |
      To be used to small instances where the basic button should be used, however without a border.
    background: "--color-primary-medium"
    fields:
      - name: file
        type: string
        example: "/images/icons/logo.svg"
