title: "Forms"
description: |
  To be used upon creating and logging into an account and when changing account details.

patterns:
  text-input:
    title: "Text input"
    description: |
      Standard text input for forms.
    background: "--color-primary-medium"
    fields:
      - name: id
        type: string
        example: name
      - name: example
        type: string
        example: Name
      - name: type
        type: string
        example: text

  basic-label:
    title: "Basic label"
    description: |
      To be used before each input section.
    background: "--color-primary-medium"

  button:
    title: "Submit button"
    background: "--color-primary-medium"

  search:
    title: "Search"
    background: "--color-primary"
    description: |
      Standard search form. To be used once per page in or near the top nav.
