title: "Cards"
description: |
  Cards are the backbone of this website. All content should be displayed on cards. Only content not found on cards are header and footer content.

patterns:
  banner:
    title: "Banner"
    description: |
      To be used on the landing page to help promote the service provided.
    fields:
      - name: heading
        type: string
        example: "Get access to our ever-expanding collection of icons"
      - name: button_text
        type: string
        example: Try Now
      - name: button_url
        type: button_url
        example: "/account/"

  alert:
    title: "Alert Banner"
    description: |
      To be used on when there is a notice or alert.
    fields:
      - name: text
        type: string
        example: "Bulk Promotion Alert"

  product-full:
    title: "Product Display"
    description: |
      Holds the icon for the products page.
    width: 20em;
    fields:
      - name: icon
        type: string
        example: "/images/icons/logo.svg"

  product-content:
    title: "Product Content"
    description: |
      Holds the description and download button for the products page.
    width: 50em;
    fields:
      - name: name
        type: string
        example: "Icon's Name"
      - name: author
        type: string
        example: "Author's Name"
      - name: collection
        type: string
        example: "Collection's Name"
      - name: file
        type: string
        example: "/images/icons/logo.svg"
      - name: license
        type: string
        example: "License"
      - name: related-searches
        type: string
        example: "Logo, IcoStash, Filler."

  product-card:
    title: "Product card"
    description: |
      This holds the main content for the website.
    width: 20em;
    fields:
      - name: name
        type: string
        example: Icon Name
      - name: image
        type: string
        example: "/images/icons/logo.svg"
        data:
          source: "site.products[0]"
          type: Product
      - name: url
        type: string
        example: "#"

  product-card-home:
    title: "Product card Home"
    description: |
      This holds the main content for the Homepage.
    width: 20em;
    fields:
      - name: text
        type: string
        example: "Blog"
      - name: image
        type: string
        example: "/images/icons/logo.svg"
        data:
          source: "site.daily[0]"
          type: daily
      - name: url
        type: string
        example: "#"

  form-horizontal:
    title: "Horizonal Form"
    description: |
      This holds a series of inputs from a form, in a horizontal layout.
    width: 50em;
    fields:
      - name: icon
        type: string
        example: logo.svg
      - name: input1_id
        type: string
        example: name
      - name: input1_example
        type: string
        example: Name
      - name: input1_type
        type: string
        example: text
      - name: input2_id
        type: string
        example: name
      - name: input2_example
        type: string
        example: Name
      - name: input2_type
        type: string
        example: text
      - name: input3_id
        type: string
        example: name
      - name: input3_example
        type: string
        example: Name
      - name: input3_type
        type: string
        example: text

  form-vertical:
    title: "Vertical Form"
    description: |
      This holds a series of inputs from a form, in a vertical layout.
    width: 20em;
    fields:
      - name: icon
        type: string
        example: logo.svg
      - name: input1_id
        type: string
        example: name
      - name: input1_example
        type: string
        example: Name
      - name: input1_type
        type: string
        example: text
      - name: input2_id
        type: string
        example: name
      - name: input2_example
        type: string
        example: Name
      - name: input2_type
        type: string
        example: text
      - name: input3_id
        type: string
        example: name
      - name: input3_example
        type: string
        example: Name
      - name: input3_type
        type: string
        example: text

  single-input:
    title: "Single Input Form"
    description: |
      This holds a single form input, in a horizontal layout.
    width: 50em;
    fields:
      - name: text
        type: string
        example: Register to our newsletter for deals and notifications.
      - name: id
        type: string
        example: email
      - name: example
        type: string
        example: email
      - name: type
        type: string
        example: email
