title: "Cards"
description: |
  Cards are the backbone of this website. All content should be displayed on cards. Only content not found on cards are header and footer content.

patterns:
  banner:
    title: "Banner"
    description: |
      To be used on the landing page to help promote the service provided.

  product:
    title: "Product card"
    description: |
      This holds the main content for the website.
    width: 20em;

  form-horizontal:
    title: "Horizonal Form"
    width: 50em;

  form-vertical:
    title: "Vertical Form"
    width: 20em;
